from django.contrib.auth.models import User
from django.core.management.base import BaseCommand
from shop.models import Category, Product, SiteSettings


class Command(BaseCommand):
    help = "Seed database with ARUN Suppliers products and categories"

    def handle(self, *args, **options):
        self.stdout.write("Seeding ARUN Suppliers database...")

        if not User.objects.filter(username="admin").exists():
            User.objects.create_superuser("admin", "admin@arunplumbing.com", "admin123")
            self.stdout.write(self.style.SUCCESS("Created admin user (admin / admin123)"))

        SiteSettings.objects.get_or_create(
            pk=1,
            defaults={
                "shop_name": "ARUN Suppliers",
                "shop_tagline": "All Plumbing & Hardware Materials in Bharatpur",
                "shop_phone": "+9779800000000",
                "shop_email": "info@arunplumbing.com",
                "shop_address": "Bharatpur 44200, Nepal",
                "shop_opening_hours": "Sun-Fri: 8:00 AM - 7:00 PM | Sat: 9:00 AM - 5:00 PM",
                "whatsapp_number": "+9779800000000",
                "free_delivery_threshold": 5000,
                "delivery_fee": 150,
                "announcement_text": "Free delivery on orders above Rs 5,000!",
            },
        )
        s = SiteSettings.objects.get(pk=1)
        updated = False
        for field, default in [
            ("shop_name", "ARUN Suppliers"),
            ("shop_tagline", "All Plumbing & Hardware Materials in Bharatpur"),
            ("shop_phone", "+9779800000000"),
            ("shop_email", "info@arunplumbing.com"),
            ("shop_address", "Bharatpur 44200, Nepal"),
            ("shop_opening_hours", "Sun-Fri: 8:00 AM - 7:00 PM | Sat: 9:00 AM - 5:00 PM"),
        ]:
            if not getattr(s, field):
                setattr(s, field, default)
                updated = True
        if updated:
            s.save()

        Product.objects.all().delete()
        Category.objects.all().delete()
        self.stdout.write("Cleared old categories and products.")

        categories_data = [
            {"name": "Pipes", "slug": "pipes", "icon": "🔧", "sort_order": 1,
             "description": "SDR11, SDR13.5 and CPVC pipes for residential and commercial plumbing"},
            {"name": "Fittings", "slug": "fittings", "icon": "⚙️", "sort_order": 2,
             "description": "CPVC couplers, elbows, tees, crosses and end caps"},
            {"name": "CPVC Adaptors", "slug": "cpvc-adaptors", "icon": "🔗", "sort_order": 3,
             "description": "Male and female threaded adaptors for CPVC pipes"},
            {"name": "Brass Adaptors", "slug": "brass-adaptors", "icon": "🔗", "sort_order": 4,
             "description": "Male, female and reducing threaded brass adaptors"},
            {"name": "Special Brass Fittings", "slug": "special-brass-fittings", "icon": "🔩", "sort_order": 5,
             "description": "Double and triple female brass fittings"},
            {"name": "Valves & Accessories", "slug": "valves-accessories", "icon": "🚰", "sort_order": 6,
             "description": "Ball valves, unions, connectors, clamps and tank fittings"},
            {"name": "Chemical", "slug": "chemical", "icon": "🧪", "sort_order": 7,
             "description": "CPVC solvent cement and adhesives"},
            {"name": "Reducers", "slug": "reducers", "icon": "📏", "sort_order": 8,
             "description": "Reducer couplings in various size combinations"},
        ]

        categories = {}
        for data in categories_data:
            cat, _ = Category.objects.update_or_create(
                slug=data["slug"], defaults=data
            )
            categories[data["slug"]] = cat
            self.stdout.write(f"  Created category: {cat.name}")

        products_data = [
            # ── Pipes ──
            {"name": "SDR11 Pipe – 3m Length", "slug": "sdr11-pipe-3m",
             "category": "pipes", "price": 180, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "SDR11 pipe for cold water supply, 3 metre length",
             "description": "SDR11 rated CPVC pipe for cold water plumbing. Smooth interior surface ensures consistent flow. Suitable for residential and light commercial water supply lines. Length: 3 metres.",
             "is_featured": True},
            {"name": "SDR13.5 Pipe – 3m Length", "slug": "sdr13-5-pipe-3m",
             "category": "pipes", "price": 150, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "SDR13.5 pipe for general plumbing, 3 metre length",
             "description": "SDR13.5 rated pipe for general-purpose plumbing applications. Durable construction with UV-resistant outer layer. Length: 3 metres.",
             "is_featured": False},
            {"name": "CPVC Schedule-40 Pipe – 3m Length", "slug": "cpvc-schedule-40-pipe-3m",
             "category": "pipes", "price": 220, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Schedule-40 CPVC pipe for hot and cold water, 3 metre length",
             "description": "CPVC Schedule-40 pipe rated for both hot and cold water. Temperature resistance up to 90°C. Ideal for kitchen and bathroom plumbing. Pressure rated. Length: 3 metres.",
             "is_featured": True},

            # ── Fittings ──
            {"name": "CPVC Coupler", "slug": "cpvc-coupler",
             "category": "fittings", "price": 15, "stock": 500,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Straight coupler for joining two CPVC pipes",
             "description": "CPVC socket coupler for joining two pipes of the same size in a straight line. Solvent cement type connection. Leak-proof and durable.",
             "is_featured": False},
            {"name": "CPVC Elbow 90°", "slug": "cpvc-elbow-90",
             "category": "fittings", "price": 18, "stock": 500,
             "unit": "piece", "brand": "ARUN",
             "short_description": "90-degree elbow for CPVC pipe connections",
             "description": "CPVC 90-degree elbow fitting for changing pipe direction at a right angle. Solvent cement type. Smooth interior for unrestricted flow.",
             "is_featured": True},
            {"name": "CPVC Reducer Elbow 90°", "slug": "cpvc-reducer-elbow-90",
             "category": "fittings", "price": 25, "stock": 300,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Reducer elbow to connect two different pipe sizes at 90°",
             "description": "CPVC reducer elbow 90-degree fitting that connects two different pipe sizes while changing direction. Solvent cement connection.",
             "is_featured": False},
            {"name": "CPVC Elbow 45°", "slug": "cpvc-elbow-45",
             "category": "fittings", "price": 20, "stock": 400,
             "unit": "piece", "brand": "ARUN",
             "short_description": "45-degree elbow for gradual pipe direction change",
             "description": "CPVC 45-degree elbow fitting for gradual changes in pipe direction. Reduces stress on pipe joints. Solvent cement type.",
             "is_featured": False},
            {"name": "CPVC Tee", "slug": "cpvc-tee",
             "category": "fittings", "price": 22, "stock": 500,
             "unit": "piece", "brand": "ARUN",
             "short_description": "T-joint for branching CPVC pipe lines",
             "description": "CPVC tee fitting for creating a three-way branch connection. All ports equal size. Solvent cement connection. Clean inner surface.",
             "is_featured": True},
            {"name": "CPVC Cross Tee", "slug": "cpvc-cross-tee",
             "category": "fittings", "price": 35, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Four-way cross tee for CPVC pipe branching",
             "description": "CPVC cross tee fitting for creating four-way pipe connections. Ideal for complex plumbing layouts. Solvent cement type.",
             "is_featured": False},
            {"name": "CPVC End Cap", "slug": "cpvc-end-cap",
             "category": "fittings", "price": 12, "stock": 500,
             "unit": "piece", "brand": "ARUN",
             "short_description": "End cap to seal the end of a CPVC pipe",
             "description": "CPVC end cap for sealing open pipe ends. Solvent cement connection. Provides a clean, leak-proof finish.",
             "is_featured": False},

            # ── CPVC Adaptors ──
            {"name": "Male Threaded Adaptor – CPVC", "slug": "mta-cpvc",
             "category": "cpvc-adaptors", "price": 28, "stock": 400,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC to male thread adaptor",
             "description": "Male threaded adaptor (MTA) for connecting CPVC pipe to a female threaded fitting. One end solvent cement, other end BSP male thread.",
             "is_featured": False},
            {"name": "Reducer MTA – CPVC", "slug": "reducer-mta-cpvc",
             "category": "cpvc-adaptors", "price": 32, "stock": 300,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Reducing male threaded adaptor for CPVC pipes",
             "description": "Reducing male threaded adaptor to connect a smaller CPVC pipe to a larger female threaded fitting. Solvent cement to male thread.",
             "is_featured": False},
            {"name": "Female Threaded Adaptor – CPVC", "slug": "fta-cpvc",
             "category": "cpvc-adaptors", "price": 28, "stock": 400,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC to female thread adaptor",
             "description": "Female threaded adaptor (FTA) for connecting CPVC pipe to a male threaded fitting. One end solvent cement, other end BSP female thread.",
             "is_featured": False},

            # ── Brass Adaptors ──
            {"name": "Male Threaded Adaptor – Brass", "slug": "mta-brass",
             "category": "brass-adaptors", "price": 45, "stock": 300,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Brass male threaded adaptor",
             "description": "Brass male threaded adaptor for connecting pipes to female threaded fittings. Durable brass construction with precision-cut BSP threads. Chrome-plated finish.",
             "is_featured": True},
            {"name": "Reducing MTA – Brass", "slug": "reducing-mta-brass",
             "category": "brass-adaptors", "price": 50, "stock": 250,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Reducing male threaded brass adaptor",
             "description": "Reducing brass male threaded adaptor to connect different pipe sizes. Precision-machined threads. Chrome-plated finish for corrosion resistance.",
             "is_featured": False},
            {"name": "Female Threaded Adaptor – Brass", "slug": "fta-brass",
             "category": "brass-adaptors", "price": 45, "stock": 300,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Brass female threaded adaptor",
             "description": "Brass female threaded adaptor for connecting male threaded fittings to pipes. Chrome-plated brass construction. Precision BSP threads.",
             "is_featured": False},
            {"name": "Reducer FTA – Brass", "slug": "reducer-fta-brass",
             "category": "brass-adaptors", "price": 50, "stock": 250,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Reducing female threaded brass adaptor",
             "description": "Reducing brass female threaded adaptor for connecting different size male threaded fittings. Chrome-plated brass construction.",
             "is_featured": False},
            {"name": "Female Threaded Elbow – Brass", "slug": "female-threaded-elbow-brass",
             "category": "brass-adaptors", "price": 65, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Brass 90° elbow with female thread",
             "description": "Brass 90-degree elbow with female threaded ends. Ideal for tight corner connections. Chrome-plated finish. Precision-cut BSP threads.",
             "is_featured": True},
            {"name": "Reducer Female Elbow – Brass", "slug": "reducer-female-elbow-brass",
             "category": "brass-adaptors", "price": 70, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Reducing brass female threaded elbow",
             "description": "Reducing brass 90-degree elbow with female threaded ends of different sizes. Chrome-plated finish for corrosion resistance.",
             "is_featured": False},
            {"name": "Female Threaded Tee – Brass", "slug": "female-threaded-tee-brass",
             "category": "brass-adaptors", "price": 75, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Brass tee with three female threaded ports",
             "description": "Brass tee fitting with three female threaded ports. Ideal for branching water lines with threaded connections. Chrome-plated finish.",
             "is_featured": False},
            {"name": "Reducer Female Tee – Brass", "slug": "reducer-female-tee-brass",
             "category": "brass-adaptors", "price": 80, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Reducing brass female threaded tee",
             "description": "Reducing brass tee with female threaded ports of different sizes. Chrome-plated brass construction. Precision-cut BSP threads.",
             "is_featured": False},

            # ── Special Brass Fittings ──
            {"name": "Double Female Elbow – Brass", "slug": "double-female-elbow-brass",
             "category": "special-brass-fittings", "price": 85, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Brass elbow with two female threaded outlets",
             "description": "Double female brass elbow for connecting two male threaded fittings at a 90-degree angle. Heavy-duty brass construction. Chrome-plated finish.",
             "is_featured": False},
            {"name": "Triple Female Elbow – Brass", "slug": "triple-female-elbow-brass",
             "category": "special-brass-fittings", "price": 110, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Brass fitting with three female threaded ports at 90°",
             "description": "Triple female brass elbow for multi-directional connections. Three female threaded ports at 90-degree angles. Chrome-plated brass. Ideal for complex plumbing layouts.",
             "is_featured": False},

            # ── Valves & Accessories ──
            {"name": "End Plug Threaded", "slug": "end-plug-threaded",
             "category": "valves-accessories", "price": 20, "stock": 400,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Threaded end plug for sealing pipe ends",
             "description": "Threaded metal end plug for sealing open pipe or fitting ends. BSP thread. Durable brass construction.",
             "is_featured": False},
            {"name": "Pipe Clamp – ABS Plastic", "slug": "pipe-clamp-abs",
             "category": "valves-accessories", "price": 10, "stock": 500,
             "unit": "piece", "brand": "ARUN",
             "short_description": "ABS plastic pipe clamp for wall mounting",
             "description": "Lightweight ABS plastic pipe clamp for securing pipes to walls and surfaces. Snap-fit design for easy installation. Available in multiple sizes.",
             "is_featured": False},
            {"name": "Metal Clamp – U-Type", "slug": "metal-clamp-u-type",
             "category": "valves-accessories", "price": 15, "stock": 500,
             "unit": "piece", "brand": "ARUN",
             "short_description": "U-type metal pipe clamp for secure mounting",
             "description": "Heavy-duty U-type metal pipe clamp for securing pipes to walls. Galvanised steel construction for rust resistance. Includes screw and anchor.",
             "is_featured": False},
            {"name": "Passover / Step Over Bend", "slug": "passover-step-over-bend",
             "category": "valves-accessories", "price": 80, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Step-over bend for crossing pipes without interference",
             "description": "Passover / step-over bend for routing one pipe over another without T-junction. CPVC construction. Smooth flow path.",
             "is_featured": False},
            {"name": "Ball Valve", "slug": "ball-valve",
             "category": "valves-accessories", "price": 180, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Full port ball valve for quick shut-off",
             "description": "Full port brass ball valve for quick quarter-turn shut-off. Chrome-plated body. PTFE seat for bubble-tight seal. Lever handle. Suitable for hot and cold water.",
             "is_featured": True},
            {"name": "Union", "slug": "union-fitting",
             "category": "valves-accessories", "price": 55, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Union fitting for easy pipe disconnection",
             "description": "Threaded union fitting for connecting and disconnecting pipes without cutting. Allows easy maintenance and repair. Chrome-plated brass.",
             "is_featured": False},
            {"name": "Tank Connector", "slug": "tank-connector",
             "category": "valves-accessories", "price": 60, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Tank connector for water tank inlet/outlet",
             "description": "Tank connector for creating watertight inlet or outlet connections on water tanks. Rubber gasket seal. Durable PVC and brass construction.",
             "is_featured": False},
            {"name": "Concealed Valve – Chrome Plated", "slug": "concealed-valve-chrome",
             "category": "valves-accessories", "price": 350, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "Chrome-plated concealed valve for hidden wall installation",
             "description": "Chrome-plated concealed valve for installation inside the wall. Quarter-turn operation. Ceramic disc cartridge. Ideal for modern bathroom installations.",
             "is_featured": True},
            {"name": "CPVC Mixer Bracket", "slug": "cpvc-mixer-bracket",
             "category": "valves-accessories", "price": 120, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC bracket for wall-mounted mixer taps",
             "description": "CPVC mixer bracket for securely mounting hot and cold water mixer taps. Pre-set pipe spacing for standard mixer taps. Durable CPVC construction.",
             "is_featured": False},

            # ── Chemical ──
            {"name": "CPVC Solvent Cement – NSF", "slug": "cpvc-solvent-cement-nsf",
             "category": "chemical", "price": 150, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "NSF-certified CPVC solvent cement",
             "description": "NSF-certified CPVC solvent cement for joining CPVC pipes and fittings. Quick-setting formula. Creates a permanent, leak-proof bond. Suitable for potable water systems.",
             "is_featured": True},

            # ── Reducers ──
            {"name": "Reducer 3/4\" × 1/2\"", "slug": "reducer-3-4-x-1-2",
             "category": "reducers", "price": 20, "stock": 300,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 3/4 inch to 1/2 inch",
             "description": "CPVC reducer coupling for connecting 3/4 inch pipe to 1/2 inch pipe. Solvent cement connection. Smooth interior for consistent flow.",
             "is_featured": False},
            {"name": "Reducer 1\" × 1/2\"", "slug": "reducer-1-x-1-2",
             "category": "reducers", "price": 30, "stock": 250,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1 inch to 1/2 inch",
             "description": "CPVC reducer coupling for connecting 1 inch pipe to 1/2 inch pipe. Solvent cement type. Durable construction.",
             "is_featured": False},
            {"name": "Reducer 1\" × 3/4\"", "slug": "reducer-1-x-3-4",
             "category": "reducers", "price": 28, "stock": 250,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1 inch to 3/4 inch",
             "description": "CPVC reducer coupling for connecting 1 inch pipe to 3/4 inch pipe. Solvent cement connection. Clean interior finish.",
             "is_featured": False},
            {"name": "Reducer 1-1/4\" × 1/2\"", "slug": "reducer-1-1-4-x-1-2",
             "category": "reducers", "price": 40, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1-1/4 inch to 1/2 inch",
             "description": "CPVC reducer coupling for connecting 1-1/4 inch pipe to 1/2 inch pipe. Solvent cement type. Smooth bore for unrestricted flow.",
             "is_featured": False},
            {"name": "Reducer 1-1/4\" × 3/4\"", "slug": "reducer-1-1-4-x-3-4",
             "category": "reducers", "price": 38, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1-1/4 inch to 3/4 inch",
             "description": "CPVC reducer coupling for connecting 1-1/4 inch pipe to 3/4 inch pipe. Solvent cement connection. Durable construction.",
             "is_featured": False},
            {"name": "Reducer 1-1/4\" × 1\"", "slug": "reducer-1-1-4-x-1",
             "category": "reducers", "price": 35, "stock": 200,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1-1/4 inch to 1 inch",
             "description": "CPVC reducer coupling for connecting 1-1/4 inch pipe to 1 inch pipe. Solvent cement type. Consistent bore for smooth flow.",
             "is_featured": False},
            {"name": "Reducer 1-1/2\" × 3/4\"", "slug": "reducer-1-1-2-x-3-4",
             "category": "reducers", "price": 45, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1-1/2 inch to 3/4 inch",
             "description": "CPVC reducer coupling for connecting 1-1/2 inch pipe to 3/4 inch pipe. Solvent cement connection. High-pressure rated.",
             "is_featured": False},
            {"name": "Reducer 1-1/2\" × 1\"", "slug": "reducer-1-1-2-x-1",
             "category": "reducers", "price": 42, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1-1/2 inch to 1 inch",
             "description": "CPVC reducer coupling for connecting 1-1/2 inch pipe to 1 inch pipe. Solvent cement type. Durable and leak-proof.",
             "is_featured": False},
            {"name": "Reducer 1-1/2\" × 1-1/4\"", "slug": "reducer-1-1-2-x-1-1-4",
             "category": "reducers", "price": 40, "stock": 150,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 1-1/2 inch to 1-1/4 inch",
             "description": "CPVC reducer coupling for connecting 1-1/2 inch pipe to 1-1/4 inch pipe. Solvent cement connection. Smooth interior finish.",
             "is_featured": False},
            {"name": "Reducer 2\" × 3/4\"", "slug": "reducer-2-x-3-4",
             "category": "reducers", "price": 60, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 2 inch to 3/4 inch",
             "description": "CPVC reducer coupling for connecting 2 inch pipe to 3/4 inch pipe. Solvent cement type. For large to small pipe transitions.",
             "is_featured": False},
            {"name": "Reducer 2\" × 1\"", "slug": "reducer-2-x-1",
             "category": "reducers", "price": 55, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 2 inch to 1 inch",
             "description": "CPVC reducer coupling for connecting 2 inch pipe to 1 inch pipe. Solvent cement connection. High-pressure rated.",
             "is_featured": False},
            {"name": "Reducer 2\" × 1-1/4\"", "slug": "reducer-2-x-1-1-4",
             "category": "reducers", "price": 52, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 2 inch to 1-1/4 inch",
             "description": "CPVC reducer coupling for connecting 2 inch pipe to 1-1/4 inch pipe. Solvent cement type. Durable CPVC construction.",
             "is_featured": False},
            {"name": "Reducer 2\" × 1-1/2\"", "slug": "reducer-2-x-1-1-2",
             "category": "reducers", "price": 50, "stock": 100,
             "unit": "piece", "brand": "ARUN",
             "short_description": "CPVC reducer 2 inch to 1-1/2 inch",
             "description": "CPVC reducer coupling for connecting 2 inch pipe to 1-1/2 inch pipe. Solvent cement connection. Smooth interior for consistent flow.",
             "is_featured": False},
        ]

        for data in products_data:
            category = categories[data.pop("category")]
            Product.objects.update_or_create(
                slug=data["slug"],
                defaults={**data, "category": category, "is_active": True},
            )
            self.stdout.write(f"  Created product: {data['name']}")

        self.stdout.write(self.style.SUCCESS(
            f"\nDone! Created {len(categories_data)} categories and {len(products_data)} products."
        ))
        self.stdout.write(self.style.SUCCESS(
            "Run the server: python manage.py runserver"
        ))
