# Generated by Django 6.0.7 on 2026-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Tax percentage (e.g. 13 for Nepal VAT)', max_digits=5),
        ),
    ]
