# Generated by Django 6.0.7 on 2026-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram (kg)'), ('meter', 'Meter'), ('inch', 'Inch'), ('foot', 'Foot'), ('yard', 'Yard'), ('liter', 'Liter'), ('box', 'Box'), ('set', 'Set'), ('roll', 'Roll'), ('pipe', 'Pipe'), ('fitting', 'Fitting'), ('custom', 'Custom')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
    ]
