# Generated by Django 6.0.7 on 2026-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productimage_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4/WebM video file', upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL'),
        ),
    ]
