# Generated by Django 6.0.7 on 2026-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productvideo_video_file_alter_productvideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shop_address',
            field=models.CharField(default='Bharatpur 44200, Nepal', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_email',
            field=models.EmailField(default='info@bharatpurplumbing.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_name',
            field=models.CharField(default='WONTA SUPPLIERS', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_opening_hours',
            field=models.CharField(default='Sun-Fri: 8:00 AM - 7:00 PM | Sat: 9:00 AM - 5:00 PM', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_phone',
            field=models.CharField(default='+9779800000000', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_tagline',
            field=models.CharField(default='All Plumbing & Hardware Materials in Bharatpur', max_length=255),
        ),
    ]
